services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./skripts:/docker-entrypoint-initdb.d
    restart: always

  elasticsearch:
    image: elasticsearch:8.14.3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'               # Ограничить до 2 CPU
          memory: '4g'               # Ограничить до 4 GB RAM
        reservations:
          cpus: '1.0'                # Зарезервировать 1 CPU
          memory: '2g'

  app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - postgres
      - elasticsearch

volumes:
  postgres_data:
