services:
  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'

  postgres:
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge